name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches: [Release]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build          # puts output in ./build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build               # uploads static site

      - uses: actions/deploy-pages@v4
        with:
          branch: gh-pages          # push to the branch you created
          clean: true               # wipe old files
